### ISSUE TITLE
PROTOCOL_SSLv3 is not defined error

### ISSUE THREAD

**Issue by FauxFaux** [pagekite/PySocksipyChain#4]
Python 2.7.9 in Debian sid (a pre-release version) is built without support for SSLv3, which causes this constant to be unavailable.  This causes the library to fail to build/run on these systems.

There's no explicit discussion about this in Debain anywhere I've seen, but the Python documentation talks about this being a possibility, and there are other people/packages experiencing this issue: https://docs.python.org/2/library/ssl.html#ssl.PROTOCOL_SSLv3

At this point, it's probably safe and easiest to just totally drop SSL3 support.

Example build log on Debian sid:
https://reproducible.debian.net/rbuild/pagekite_0.5.6d-3.rbuild.log

```
make[1]: Entering directory '/tmp/buildd/pagekite-0.5.6d'
make doc/pagekite.1
make[2]: Entering directory '/tmp/buildd/pagekite-0.5.6d'
Traceback (most recent call last):
  File "./pagekite/manual.py", line 9, in <module>
    from compat import ts_to_iso
  File "/tmp/buildd/pagekite-0.5.6d/pagekite/compat.py", line 117, in <module>
    import sockschain
  File "/usr/lib/python2.7/dist-packages/sockschain/__init__.py", line 130, in <module>
    class SSL(object):
  File "/usr/lib/python2.7/dist-packages/sockschain/__init__.py", line 132, in SSL
    SSLv3_METHOD = ssl.PROTOCOL_SSLv3
AttributeError: 'module' object has no attribute 'PROTOCOL_SSLv3'
Makefile:59: recipe for target 'doc/pagekite.1' failed
```

**Comment by SunilMohanAdapa** [comment]
I have made pull request for this in #5.

**Comment by pagekite** [comment]
This was fixed quite some time ago. Sorry this repo has been ignored, thank you for your report.
